### Login to get a fresh token
# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "Kyle"
}

### Use the token from login in Authorization header
GET http://localhost:3000/posts
Authorization: Bearer {{login.response.body.accessToken}}
